import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const snapshotDate = "2026-08-09";
const labelRoot = path.join(root, "data", "labeling", "jeju", snapshotDate);
const baselinePath = path.join(labelRoot, "place-preference-label-v4-reviewed", "place_labels.jsonl");
const reviewsPath = path.join(labelRoot, "place-preference-label-v5-researched", "reviews");
const outputPath = path.join(root, "review-ui", "data", "v5-researched-data.js");

const baseline = fs.readFileSync(baselinePath, "utf8").trim().split(/\r?\n/u).map((line) => JSON.parse(line));
const reviewFiles = new Map(
  fs.readdirSync(reviewsPath)
    .filter((name) => name.endsWith(".json"))
    .map((name) => [name.slice(0, -5), path.join(reviewsPath, name)]),
);

const groupFor = (label) => label.split(".")[0];
const normalizeLabel = (label, record) => ({
  label,
  group: groupFor(label),
  value: record.value,
  confidence: record.confidence ?? null,
  status: record.review_status ?? "confirmed",
  rationale: record.rationale ?? record.calculation ?? "",
  hold_reason: record.hold_reason ?? "",
  source_ids: record.source_ids ?? [],
  calculation: record.calculation ?? "",
  input_labels: record.input_labels ?? [],
});

const labelsFromReview = (review) => {
  if (review.atomic_labels) {
    return {
      atomic: Object.entries(review.atomic_labels),
      derived: Object.entries(review.derived_labels ?? review.derived_style ?? {}),
    };
  }
  return {
    atomic: [
      ...Object.entries(review.theme ?? {}).map(([key, value]) => [`theme.${key}`, value]),
      ...Object.entries(review.environment ?? {}).map(([key, value]) => [`environment.${key}`, value]),
      ...Object.entries(review.style_evidence ?? {}).map(([key, value]) => [`style_evidence.${key}`, value]),
    ],
    derived: Object.entries(review.derived_style ?? {}).map(([key, value]) => [`derived_style.${key}`, value]),
  };
};

const places = baseline.map((base) => {
  const reviewPath = reviewFiles.get(String(base.contentid));
  if (!reviewPath) throw new Error(`v5 review 없음: ${base.contentid}`);
  const review = JSON.parse(fs.readFileSync(reviewPath, "utf8"));
  const { atomic, derived } = labelsFromReview(review);
  if (atomic.length !== 18 || derived.length !== 6) {
    throw new Error(`${base.contentid}: 라벨 수가 18+6이 아닙니다 (${atomic.length}+${derived.length})`);
  }
  return {
    contentid: String(base.contentid),
    title: review.title || base.title,
    reviewed_at: review.reviewed_at,
    source_place: review.source_place ?? base.source_place ?? {},
    labels: [...atomic, ...derived].map(([label, record]) => normalizeLabel(label, record)),
    sources: review.sources ?? [],
  };
});

if (places.length !== 1664 || reviewFiles.size !== 1664) {
  throw new Error(`v5 뷰어 입력 건수 불일치: places=${places.length}, reviewFiles=${reviewFiles.size}`);
}

const payload = {
  schema_version: "place-preference-label-v5-researched-viewer-data-v1",
  snapshot_date: snapshotDate,
  label_version: "place-preference-label-v5-researched",
  score_scale: [0, 0.25, 0.5, 0.75, 1],
  place_count: places.length,
  places,
};

fs.writeFileSync(
  outputPath,
  `/* Generated by scripts/build_v5_researched_viewer_data.mjs. Do not edit. */\nwindow.JEJU_V5_RESEARCHED_DATA = ${JSON.stringify(payload)};\n`,
  "utf8",
);
console.log(`v5 viewer bundle: ${places.length} places -> ${path.relative(root, outputPath)}`);
